# Set UTF-8 locale early (required for Powerlevel10k on Linux)
if [[ -z "$LANG" || "$LANG" == "C" || "$LANG" == "POSIX" ]]; then
    export LANG=en_US.UTF-8
fi

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Auto-detect setup directory by resolving the .zshrc symlink
if [[ -L "$HOME/.zshrc" ]]; then
    SETUP_DIR="${$(readlink "$HOME/.zshrc"):h:h}"
else
    SETUP_DIR="${${(%):-%x}:A:h:h}"
fi
# Exported so tmux and child scripts resolve repository paths the same way.
export SETUP_DIR

# Source a Zsh file through its compiled .zwc copy, recompiling when stale.
# Compiling makes the large helper files load in well under a millisecond.
_setup_source() {
    local file="$1" compiled="$1.zwc" staged="$1.$$.zwc"
    [[ -r "$file" ]] || return 0
    # Compile to a private name and rename, so concurrent shells never read a
    # half-written file. zcompile requires the .zwc suffix on its output.
    if [[ ! -s "$compiled" || "$file" -nt "$compiled" ]] && [[ -w "${file:h}" ]]; then
        { zcompile -R -- "$staged" "$file" && command mv -f -- "$staged" "$compiled" } 2>/dev/null ||
            command rm -f -- "$staged" 2>/dev/null
    fi
    source "$file"
}

# Load local, per-machine setup choices generated by setup.sh --fix.
SETUP_ENV_FILE="${SETUP_LOCAL_ENV_FILE:-$SETUP_DIR/.local/.env.zsh}"
[[ -r "$SETUP_ENV_FILE" ]] && source "$SETUP_ENV_FILE"
WORK_ENV="${WORK_ENV:-false}"

if [[ "$WORK_ENV" == true && -z "${JOB:-}" ]]; then
    echo "Warning: WORK_ENV=true but JOB is not set in $SETUP_ENV_FILE"
    WORK_ENV=false
fi
# A work overlay is a separate checkout: WORK_ROOT holds $JOB/ with its tools.
if [[ "$WORK_ENV" == true && ! -d "${WORK_ROOT:-}/$JOB" ]]; then
    echo "Warning: WORK_ENV=true but the work overlay ${WORK_ROOT:+$WORK_ROOT/}$JOB is missing; set WORK_ROOT in $SETUP_ENV_FILE"
    WORK_ENV=false
fi

DOTFILE_DIR="$SETUP_DIR/dotfiles"
WORK_DIR=""
if [[ "$WORK_ENV" == true ]]; then
    # Exported so tmux, Git and reinstall-apps find the overlay hooks.
    export WORK_ROOT JOB WORK_DIR="$WORK_ROOT/$JOB"
    if [[ -z "${SETUP_PYTHON_VENV:-}" && -x "$SETUP_DIR/.local/${JOB}-venv/bin/python" ]]; then
        export SETUP_PYTHON_VENV="$SETUP_DIR/.local/${JOB}-venv"
    fi
fi

# Login shells load .zprofile before .zshrc. Source it only as a fallback for
# non-login interactive shells so Homebrew paths are available before compinit.
if [[ -z "${HOMEBREW_PREFIX:-}" && -r "$DOTFILE_DIR/.zprofile" ]]; then
    source "$DOTFILE_DIR/.zprofile"
fi

# FPATH can inherit a stale Zsh version. Put this shell's matching functions
# directory first, then retain one copy of every completion path.
if [[ "$OSTYPE" == darwin* && "$ZSH_ARGZERO" == /bin/zsh ]]; then
    zsh_functions_dir="/usr/share/zsh/$ZSH_VERSION/functions"
else
    zsh_functions_dir="${commands[zsh]:A:h:h}/share/zsh/functions"
fi
if [[ -d "$zsh_functions_dir" ]]; then
    fpath=("$zsh_functions_dir" "${fpath[@]}")
fi
fpath=("${(@u)fpath}")
unset zsh_functions_dir

# PATH
typeset -gU path PATH
if [[ "$WORK_ENV" == true ]]; then
    path=("$WORK_DIR/bin-$JOB" "${path[@]}")
fi
if [[ -n "${SETUP_PYTHON_VENV:-}" && -d "$SETUP_PYTHON_VENV/bin" ]]; then
    path=("$SETUP_PYTHON_VENV/bin" "${path[@]}")
fi
path=("$DOTFILE_DIR/.bin" "$HOME/.local/bin" "${path[@]}")
export PATH

fzf_setup() {
    # fzf (cached init for faster startup)
    local fzf_bin="${commands[fzf]-}"
    local _fzf_cache
    if [[ -n "$fzf_bin" ]]; then
        _fzf_cache="$HOME/.cache/fzf-init.zsh"
        if [[ ! -f "$_fzf_cache" || "$fzf_bin" -nt "$_fzf_cache" ]]; then
            fzf --zsh > "$_fzf_cache"
        fi
        source "$_fzf_cache"
    else
        echo "⚠️ fzf not found! Consider installing via brew install fzf"
    fi

    if [[ -f "$HOME/.fzf-tab/fzf-tab.plugin.zsh" ]]; then
        source "$HOME/.fzf-tab/fzf-tab.plugin.zsh"
    fi

    # fzf-tab config
    zstyle ':fzf-tab:*' use-fzf-default-opts yes
    zstyle ':completion:*:descriptions' format '[%d]'
    zstyle ':completion:*' menu select
    zstyle ':completion:*' list-dirs-first true
    zstyle ':fzf-tab:*' fzf-command fzf
    zstyle ':fzf-tab:*' fzf-bindings 'tab:down,shift-tab:up'
    zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls -alhG --color=always $word'
    zstyle ':fzf-tab:complete:ls:*' fzf-preview 'ls -alhG --color=always $realpath'
    zstyle ':fzf-tab:complete:bat:*' fzf-preview 'bat --style=plain --theme="gruvbox-dark" --color=always $realpath'
    zstyle ':completion:*:*:cd:*' ignored-patterns ''
    zstyle ':completion:*:cd:*' hidden all

    setopt globdots             # include dotfiles in filename globs like *

    export FZF_DEFAULT_OPTS="
    --height=40%
    --layout=reverse
    --border=rounded
    --color=fg:#dcdccc,bg:#1c1c1c,preview-bg:#1c1c1c,border:#5f5faf,header:#af87d7
    --prompt='❯ '
    --marker='✓ '
    --pointer='>'
    --info=inline
    --bind 'tab:down,shift-tab:up'
    "
    # Preview only the file picker; history and completion items are not files.
    export FZF_CTRL_T_OPTS="--preview 'bat --style=plain --theme=gruvbox-dark --color=always --line-range :500 {}'"
}

load_base_env() {
    # Colorful grep
    export GREP_COLORS='1;35;40'

    # less command like vim
    export LESS='-F -R -M -i -N -j5 -X'

    # ls command colors
    export LSCOLORS="ExGxxxxxCxxxxxxxxxxxxx"

    # auto complete (rebuild dump once per day, use cache otherwise)
    autoload -Uz compinit
    local zcompdump="${ZDOTDIR:-$HOME}/.zcompdump"
    local -a zcompdump_old
    zcompdump_old=("$zcompdump"(N.mh+24))
    if [[ ! -f "$zcompdump" || ${#zcompdump_old[@]} -gt 0 ]]; then
        compinit
    else
        compinit -C
    fi

    # load fzf function
    fzf_setup

    # allow prompt updates ie date/time
    setopt PROMPT_SUBST

    # make '#' work in interactive shells
    setopt INTERACTIVE_COMMENTS

    _setup_source "$DOTFILE_DIR/.aliases"
    local functions_file
    for functions_file in "$DOTFILE_DIR"/functions/*.zsh(N); do
        _setup_source "$functions_file"
    done
    if [[ "$WORK_ENV" == true ]]; then
        for functions_file in "$WORK_DIR"/functions/*.zsh(N); do
            _setup_source "$functions_file"
        done
    fi

    # Load each Homebrew plugin independently from the active prefix.
    local brew_share="${HOMEBREW_PREFIX:+$HOMEBREW_PREFIX/share}"
    if [[ -n "$brew_share" ]]; then
        [[ -r "$brew_share/powerlevel10k/powerlevel10k.zsh-theme" ]] &&
            source "$brew_share/powerlevel10k/powerlevel10k.zsh-theme"
        [[ -r "$brew_share/zsh-autosuggestions/zsh-autosuggestions.zsh" ]] &&
            source "$brew_share/zsh-autosuggestions/zsh-autosuggestions.zsh"
    fi

    # To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
    _setup_source "$HOME/.p10k.zsh"

    HISTFILE=~/.zsh_history
    HISTSIZE=50000
    SAVEHIST=50000
    setopt INC_APPEND_HISTORY SHARE_HISTORY

    _gcm_expand() {
      if [[ $LBUFFER == "gcm" ]]; then
        LBUFFER='git commit -m "'
        RBUFFER='"'
      else
        zle fzf-tab-complete  # Use fzf-tab for completion
      fi
    }
    zle -N _gcm_expand
    bindkey '\t' _gcm_expand

    _toolbox_init
    _setup_atuin_init

    # zsh-syntax-highlighting must load after every other widget is defined.
    [[ -n "$brew_share" && -r "$brew_share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" ]] &&
        source "$brew_share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
}

if [[ "$WORK_ENV" == true ]]; then
    [[ -r "$WORK_DIR/.env.zsh" ]] && source "$WORK_DIR/.env.zsh"
    _setup_source "$WORK_DIR/.aliases-$JOB"
    _setup_source "$WORK_DIR/bin-$JOB/functions-$JOB.sh"
fi

load_base_env

if (( $+functions[_setup_refresh_forwarded_ssh_agent] )); then
    _setup_refresh_forwarded_ssh_agent
    unfunction _setup_refresh_forwarded_ssh_agent _setup_ssh_agent_responds
fi

# Any other work shell setup runs last, so it can override the defaults above.
[[ "$WORK_ENV" == true ]] && _setup_source "$WORK_DIR/zshrc.zsh"
