"""Embed the vendored SVGs as vector PDFs; run only when updating Octicons.

Requires svglib==1.5.1 and reportlab==4.4.10 in a development environment.
The app and its normal build have no Python or SVG-converter dependency.
"""

import argparse
import base64
import io
from pathlib import Path

def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        epilog="Example: python apps/lib/octicons/generate-octicons.py",
    )
    parser.parse_args()
    from reportlab.graphics import renderPDF
    from reportlab.pdfgen.canvas import Canvas
    from svglib.svglib import svg2rlg

    root = Path(__file__).resolve().parent
    lines = [
        '// Generated by generate-octicons.py. Do not edit the embedded PDFs.',
        '// GitHub Octicons, MIT license; see LICENSE and REVISION in this directory.',
        'import AppKit',
        'import SwiftUI',
        '',
        '@MainActor',
        'enum Octicons {',
        '    private static let images: [String: NSImage] = encoded.mapValues { value in',
        '        let image = NSImage(data: Data(base64Encoded: value)!)!',
        '        image.size = NSSize(width: 16, height: 16)',
        '        image.isTemplate = true',
        '        return image',
        '    }',
        '',
        '    static func image(_ name: String) -> NSImage? { images[name] }',
        '    static func swiftUIImage(_ name: String) -> Image {',
        '        Image(nsImage: images[name] ?? images["dot"]!)',
        '    }',
        '',
        '    private static let encoded: [String: String] = [',
    ]
    for svg in sorted(root.glob('*-16.svg')):
        drawing = svg2rlg(str(svg))
        assert drawing is not None and drawing.width == drawing.height == 16
        output = io.BytesIO()
        canvas = Canvas(output, pagesize=(16, 16), invariant=True, pageCompression=1)
        renderPDF.draw(drawing, canvas, 0, 0)
        canvas.showPage()
        canvas.save()
        encoded = base64.b64encode(output.getvalue()).decode('ascii')
        lines.append(f'        "{svg.stem.removesuffix("-16")}": "{encoded}",')
    lines += ['    ]', '}', '']
    (root / 'Octicons.swift').write_text('\n'.join(lines))


if __name__ == "__main__":
    main()
